services:
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app/uploads:/app/app/uploads
    restart: unless-stopped
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/docs"]
      interval: 30s
      timeout: 30s
      retries: 5
    command:
      [
        "uvicorn",
        "app.main:app",
        "--reload",
        "--port",
        "8000",
        "--host",
        "0.0.0.0",
      ]

networks:
  rag-network:
    driver: bridge
